spring:
  redis:
    jedis:
      pool:
        max-idle: 5
        max-active: 10
        #最大等待时间
        max-wait: 2000
    port: 6379
    host: 127.0.0.1
    #连接超时时间
    timeout: 1000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiyan?characterEncoding=utf8
    username: root
    password: qq991264921
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM dual
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
  jpa:
    show-sql: true        #显示sql语句
    hibernate:
      ddl-auto: update    #更新或者创建数据表结构
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  servlet:
    multipart:
      enabled: true
      #限制单次上传文件的大小
      max-file-size: 1MB
      #限制上传文件和的大小
      max-request-size: 200MB

server:
  port: 80
  tomcat:
    max-threads: 500
    max-connections: 1000
  servlet:
    session:
      timeout: 3600
mybatis-plus:
  type-aliases-package: org.opens.mybatisplus.dao
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      db-type: mysql
  configuration:
    #配置slq打印日志
    #只是为了本地开发调试用的，部署到生产环境，千万别打开这种sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl